spring.application.name=com.whatsapp
server.port=${PORT:8080}

excel.source=https://1drv.ms/x/c/e53940a2fd6975f5/IQCg4MIHkEpaRKUuE8uMUJn7AcrpuHn2vF9-Nl_J40sUOGM?e=xxJWym

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}

twilio.whatsapp.from=whatsapp:+917794818983
twilio.whatsapp.template.sid=HXbf72077c045b23aeb27ce9724a7714dd
twilio.status.callback.url=https://whatsapp-chatbot-keyh.onrender.com/api/twilio/status