spring.application.name=com.whatsapp
server.port=${PORT:8080}

excel.source=D:/Ekip/contacts.xlsx

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}

twilio.whatsapp.from=whatsapp:+917794818983
twilio.whatsapp.template.sid=HXYOUR_APPROVED_TEMPLATE_SID
twilio.status.callback.url=https://whatsapp-chatbot-keyh.onrender.com/api/twilio/status