spring.application.name=com.whatsapp

# Render dynamic port
server.port=${PORT:8080}

# Excel path
excel.source=D:/Ekip/contacts.xlsx

# Twilio credentials from Render Environment Variables
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}

# Production WhatsApp sender number
twilio.whatsapp.from=whatsapp:+14155238886

# Approved WhatsApp template SID
twilio.whatsapp.template.sid=HXxxxxxxxxxxxxxxxxxxxxxxxx